name: dodge-the-creeps
author: Heitor Toledo Lassarote de Paula
maintainer: heitortoledo@hotmail.com
github: heitor-lassarote/dodge-the-creeps
copyright: Heitor Toledo Lassarote de Paula 2021
version: '0.0.0.0'
license: BSD3

extra-source-files:
  - ChangeLog.md
  - README.md

dependencies:
  - base >=4.12 && <5
  - containers
  - godot-haskell
  - lens
  - linear
  - random
  - stm
  - template-haskell
  - text
  - th-abstraction
  - vector

library:
  source-dirs:
    - src
    - game

  exposed-modules:
    - Lib

  default-extensions:
    - AllowAmbiguousTypes
    - BlockArguments
    - DataKinds
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - ImportQualifiedPost
    - MultiParamTypeClasses
    - MultiWayIf
    - OverloadedStrings
    - ScopedTypeVariables
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies

  ghc-options: -Wall -Wno-orphans -fwarn-unused-do-bind -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -O2

verbatim: |

  foreign-library dodge-the-creeps
    type: native-shared
    other-modules: FLib
    hs-source-dirs: ffi/flib
    c-sources: ffi/cbits/flib.c
    build-depends:
        base >= 4.12 && <5
      , godot-haskell
      , dodge-the-creeps
      , text
    default-language: Haskell2010
