-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

module Project.Requirements where
import Project.Support

type Nodes = '[OneResourceNode "Main" "Main", OneResourceNode "Player" "Player"]
